
language: r
cache: packages
sudo: false

# Test on 3 versions of R.
r:
  - release
  - devel
  - oldrel

# Test on both linux and OSX.
# See details at https://docs.travis-ci.com/user/multi-os/
os:
  - linux
  - osx

# Allow failures on OSX.
matrix:
  allow_failures:
    - os: osx

##########################
# Code coverage

r_github_packages:
 - jimhester/covr

after_success:
 - Rscript -e 'covr::codecov()'
