# Example: https://github.com/krlmlr/r-appveyor/blob/master/appveyor.yml
# Details: https://www.appveyor.com/docs/appveyor-yml/
# OS details: https://www.appveyor.com/docs/build-environment/#operating-system

# DO NOT CHANGE the "init" and "install" sections below
init:
  ps: |
        Get-Date
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        #Import-Module '..\appveyor-tool.ps1'

install:
  ps: |
        Import-Module '..\appveyor-tool.ps1'
        Bootstrap

# Adapt as necessary starting from here

build_script:
  - git config --global user.name "travis"
  - git config --global user.email "travis@example.org"
  - travis-tool.sh install_deps
  - travis-tool.sh github_package jimhester/covr

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

# Don't check test coverage on appveyor, just use Travis-CI results.
#on_success:
#  - Rscript -e 'covr::codecov()'

environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    _R_CHECK_FORCE_SUGGESTS_: 0
    R_ARCH: x64
    USE_RTOOLS: true ## to be able to use Remotes (i.e. packages from non-CRAN sources)

  matrix:
  # Test with 3 versions of R.
    - R_VERSION: release
    - R_VERSION: devel
    - R_VERSION: stable

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

cache:
  - C:\RLibrary
